DELETE FROM axioms;
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX001', 'Quadratic Formula', 'x = [-b ± √(b²-4ac)]/2a', 'algebra', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX002', 'Binomial Theorem', '(x+y)ⁿ = ΣC(n,k)xⁿ⁻ᵏyᵏ', 'algebra', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX003', 'Matrix Determinant', 'det(A) = Σ sgn(σ)Πa_{i,σ(i)}', 'algebra', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX004', 'Eigenvalue Equation', 'Av = λv', 'algebra', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX005', 'Cramer''s Rule', 'xᵢ = det(Aᵢ)/det(A)', 'algebra', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX006', 'Vector Cross Product', 'a × b = |a||b|sinθ n', 'algebra', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX007', 'Dot Product', 'a·b = |a||b|cosθ', 'algebra', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX008', 'Cauchy-Schwarz', '|⟨u,v⟩|² ≤ ⟨u,u⟩·⟨v,v⟩', 'algebra', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX009', 'Pythagorean Theorem', 'a² + b² = c²', 'geometry', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX010', 'Circle Area', 'A = πr²', 'geometry', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX011', 'Sphere Volume', 'V = 4/3πr³', 'geometry', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX012', 'Law of Cosines', 'c² = a² + b² - 2ab cosγ', 'geometry', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX013', 'Heron''s Formula', 'A = √[s(s-a)(s-b)(s-c)]', 'geometry', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX014', 'Euler''s Formula', 'e^{iπ} + 1 = 0', 'geometry', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX015', 'Derivative Definition', 'dy/dx = lim_{Δx→0} Δy/Δx', 'calculus', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX016', 'Power Rule', 'd/dx(xⁿ) = n·xⁿ⁻¹', 'calculus', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX017', 'Chain Rule', 'dy/dx = dy/du · du/dx', 'calculus', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX018', 'Integration', '∫f(x)dx = F(b) - F(a)', 'calculus', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX019', 'Taylor Series', 'f(x) = Σ f⁽ⁿ⁾(a)/n! (x-a)ⁿ', 'calculus', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX020', 'L''Hôpital''s Rule', 'lim f/g = lim f''/g''', 'calculus', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX021', 'Euler Characteristic', 'V - E + F = 2', 'topology', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX022', 'Betti Numbers', 'β₀, β₁, β₂, ...', 'topology', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX023', 'Fundamental Group', 'π₁(X)', 'topology', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX024', 'Jordan Curve Theorem', 'Simple closed curve divides plane', 'topology', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX025', 'Brouwer Fixed Point', 'Continuous f: Dⁿ→Dⁿ has fixed point', 'topology', 'mathematics', 'Pure Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX026', 'Fourier Transform', 'F(ω) = ∫ f(t)e^{-iωt}dt', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX027', 'Laplace Transform', 'F(s) = ∫ f(t)e^{-st}dt', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX028', 'Convolution', '(f*g)(t) = ∫ f(τ)g(t-τ)dτ', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX029', 'Green''s Function', 'Lu = f → u = ∫ Gf', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX030', 'Wave Equation', '∂²u/∂t² = c²∇²u', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX031', 'Heat Equation', '∂u/∂t = α∇²u', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX032', 'Laplace''s Equation', '∇²u = 0', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX033', 'Poisson''s Equation', '∇²u = f', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX034', 'Euler-Lagrange', '∂L/∂f - d/dx(∂L/∂f'') = 0', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX035', 'Hamilton''s Equations', 'dq/dt = ∂H/∂p, dp/dt = -∂H/∂q', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX036', 'Legendre Transform', 'f*(p) = sup(px - f(x))', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX037', 'Dirac Delta', '∫ δ(x)f(x)dx = f(0)', 'applied', 'mathematics', 'Applied Mathematics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX038', 'Normal Distribution', 'f(x) = 1/(σ√2π) e^{-(x-μ)²/(2σ²)}', 'statistics', 'mathematics', 'Statistics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX039', 'Bayes'' Theorem', 'P(A|B) = P(B|A)P(A)/P(B)', 'statistics', 'mathematics', 'Statistics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX040', 'Linear Regression', 'y = β₀ + β₁x + ε', 'statistics', 'mathematics', 'Statistics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX041', 'Maximum Likelihood', 'L(θ) = Π f(xᵢ|θ)', 'statistics', 'mathematics', 'Statistics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX042', 'Central Limit Theorem', 'CLT: Sample mean ≈ Normal', 'statistics', 'mathematics', 'Statistics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX043', 'Law of Large Numbers', 'LLN: Sample mean → population mean', 'statistics', 'mathematics', 'Statistics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX044', 'Chi-Square', 'χ² = Σ (O-E)²/E', 'statistics', 'mathematics', 'Statistics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX045', 'ANOVA', 'F = MSB/MSW', 'statistics', 'mathematics', 'Statistics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX046', 'Newton''s Second Law', 'F = ma', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX047', 'Newton''s Law of Gravitation', 'F = G·m₁m₂/r²', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX048', 'Hooke''s Law', 'F = -kx', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX049', 'Kinetic Energy', 'KE = ½mv²', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX050', 'Potential Energy', 'PE = mgh', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX051', 'Work', 'W = F·d', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX052', 'Power', 'P = F·v', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX053', 'Momentum', 'p = mv', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX054', 'Impulse', 'J = F·Δt = Δp', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX055', 'Angular Momentum', 'L = Iω', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX056', 'Torque', 'τ = r × F', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX057', 'Moment of Inertia', 'I = Σ mᵢrᵢ²', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX058', 'Simple Harmonic Motion', 'x = A cos(ωt + φ)', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX059', 'Damped Oscillator', 'mẍ + cẋ + kx = 0', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX060', 'Driven Oscillator', 'mẍ + cẋ + kx = F₀ cos(ωt)', 'mechanics', 'physics', 'Classical Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX061', 'First Law', 'ΔU = Q - W', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX062', 'Second Law', 'ΔS ≥ 0', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX063', 'Third Law', 'S→0 as T→0', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX064', 'Ideal Gas Law', 'PV = nRT', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX065', 'Van der Waals', '(P + a/V²)(V - b) = RT', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX066', 'Carnot Efficiency', 'η = 1 - T₂/T₁', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX067', 'Entropy', 'ΔS = ∫dQ/T', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX068', 'Enthalpy', 'H = U + PV', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX069', 'Gibbs Free Energy', 'G = H - TS', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX070', 'Helmholtz Free Energy', 'F = U - TS', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX071', 'Maxwell Relations', '(∂T/∂V)ₛ = -(∂P/∂S)ᵥ', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX072', 'Heat Capacity', 'C = dQ/dT', 'thermo', 'physics', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX073', 'Coulomb''s Law', 'F = k·q₁q₂/r²', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX074', 'Gauss''s Law', '∮E·dA = Q/ε₀', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX075', 'Gauss''s Law for Magnetism', '∮B·dA = 0', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX076', 'Faraday''s Law', '∮E·dl = -dΦ_B/dt', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX077', 'Ampère''s Law', '∮B·dl = μ₀I', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX078', 'Maxwell–Ampère', '∮B·dl = μ₀I + μ₀ε₀ dΦ_E/dt', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX079', 'Lorentz Force', 'F = q(E + v × B)', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX080', 'Biot-Savart Law', 'dB = (μ₀/4π) I dl × r̂/r²', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX081', 'Electric Potential', 'V = kq/r', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX082', 'Capacitance', 'C = Q/V', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX083', 'Inductance', 'L = Φ/I', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX084', 'LC Circuit', 'ω = 1/√(LC)', 'em', 'physics', 'Electromagnetism');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX085', 'Schrödinger Equation', 'iℏ∂ψ/∂t = Ĥψ', 'quantum', 'physics', 'Quantum Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX086', 'Time-Independent SE', 'Ĥψ = Eψ', 'quantum', 'physics', 'Quantum Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX087', 'Heisenberg Uncertainty', 'ΔxΔp ≥ ℏ/2', 'quantum', 'physics', 'Quantum Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX088', 'Wave Function', 'ψ(x,t)', 'quantum', 'physics', 'Quantum Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX089', 'Probability Density', '|ψ|²', 'quantum', 'physics', 'Quantum Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX090', 'Expectation Value', '⟨A⟩ = ∫ψ*Âψ dτ', 'quantum', 'physics', 'Quantum Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX091', 'Commutator', '[Â,Ĉ] = ÂĈ - ĈÂ', 'quantum', 'physics', 'Quantum Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX092', 'Pauli Exclusion Principle', 'No two identical fermions share quantum state', 'quantum', 'physics', 'Quantum Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX093', 'Dirac Equation', '(iγᵘ∂ᵘ - m)ψ = 0', 'quantum', 'physics', 'Quantum Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX094', 'Path Integral', '⟨x_f|e^{-iHt/ℏ}|x_i⟩ = ∫𝒟x e^{iS[x]/ℏ}', 'quantum', 'physics', 'Quantum Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX095', 'Snell''s Law', 'n₁sinθ₁ = n₂sinθ₂', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX096', 'Fresnel Equations', 'R = |(n₁-n₂)/(n₁+n₂)|²', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX097', 'Brewster''s Angle', 'tan θ_B = n₂/n₁', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX098', 'Malus'' Law', 'I = I₀ cos²θ', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX099', 'Beer-Lambert Law', 'I = I₀ e^{-αx}', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX100', 'Bragg''s Law', 'nλ = 2d sinθ', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX101', 'Lensmaker''s Equation', '1/f = (n-1)(1/R₁ - 1/R₂)', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX102', 'Thin Lens Equation', '1/f = 1/s + 1/s''', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX103', 'Rayleigh Criterion', 'θ = 1.22λ/D', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX104', 'Diffraction Grating', 'd sinθ = mλ', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX105', 'Double Slit', 'I = I₀ cos²(πd sinθ/λ)', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX106', 'Planck''s Law', 'B(λ,T) = (2hc²/λ⁵)/(e^{hc/λkT}-1)', 'optics', 'physics', 'Optics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX107', 'Wave Equation', '∂²p/∂t² = c²∇²p', 'acoustics', 'physics', 'Acoustics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX108', 'Doppler Effect', 'f'' = f(v/(v±vₛ))', 'acoustics', 'physics', 'Acoustics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX109', 'Sound Intensity', 'I = p²/ρc', 'acoustics', 'physics', 'Acoustics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX110', 'Decibel', 'L = 10 log₁₀(I/I₀)', 'acoustics', 'physics', 'Acoustics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX111', 'Arrhenius Equation', 'k = A e^{-Ea/(RT)}', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX112', 'Eyring Equation', 'k = (k_BT/h) e^{-ΔG‡/(RT)}', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX113', 'Van''t Hoff Equation', 'ln(K₂/K₁) = (ΔH/R)(1/T₁ - 1/T₂)', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX114', 'Nernst Equation', 'E = E° - (RT/nF) ln Q', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX115', 'Butler-Volmer', 'i = i₀(e^{αnFη/(RT)} - e^{-(1-α)nFη/(RT)})', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX116', 'Debye-Hückel', 'log γ = -A|z⁺z⁻|√I', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX117', 'Langmuir Isotherm', 'θ = KP/(1+KP)', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX118', 'BET Isotherm', 'V = V_m·C·P/[(P₀-P)(1+(C-1)P/P₀)]', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX119', 'Gibbs Adsorption', 'Γ = -(1/RT)(dγ/d ln c)', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX120', 'Kohlrausch''s Law', 'Λ_m = Λ_m° - K√c', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX121', 'Stokes-Einstein', 'D = k_BT/(6πηr)', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX122', 'Einstein Relation', 'μ = qD/(k_BT)', 'physical', 'chemistry', 'Physical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX123', 'Markovnikov''s Rule', 'Addition to alkene follows Markovnikov''s rule', 'organic', 'chemistry', 'Organic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX124', 'Hammond''s Postulate', 'Transition state resembles nearest stable species', 'organic', 'chemistry', 'Organic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX125', 'Curtin-Hammett Principle', 'Product ratios determined by transition state energies', 'organic', 'chemistry', 'Organic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX126', 'Woodward-Hoffmann Rules', 'Conservation of orbital symmetry', 'organic', 'chemistry', 'Organic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX127', 'Baldwin''s Rules', 'Ring closure preferences', 'organic', 'chemistry', 'Organic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX128', 'Evans pK_a Table', 'pKa predictions based on structure', 'organic', 'chemistry', 'Organic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX129', 'Hammett Equation', 'log(K/K₀) = ρσ', 'organic', 'chemistry', 'Organic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX130', 'Taft Equation', 'log(K/K₀) = ρ*σ* + δE_s', 'organic', 'chemistry', 'Organic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX131', 'Winstein Spectrum', 'Ion pair mechanisms in SN1 reactions', 'organic', 'chemistry', 'Organic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX132', 'HSAB Principle', 'Hard and Soft Acids and Bases', 'organic', 'chemistry', 'Organic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX133', 'Crystal Field Theory', 'Δ = 10Dq', 'inorganic', 'chemistry', 'Inorganic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX134', 'Ligand Field Theory', 'Molecular orbital approach to coordination', 'inorganic', 'chemistry', 'Inorganic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX135', 'Tanabe-Sugano Diagrams', 'Energy level diagrams for dⁿ ions', 'inorganic', 'chemistry', 'Inorganic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX136', 'Orgel Diagrams', 'Correlation diagrams for transition metals', 'inorganic', 'chemistry', 'Inorganic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX137', 'Walsh Diagrams', 'Molecular orbital diagrams', 'inorganic', 'chemistry', 'Inorganic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX138', '18-Electron Rule', 'Stable organometallic compounds have 18 e⁻', 'inorganic', 'chemistry', 'Inorganic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX139', 'Wade''s Rules', 'Electron counting for clusters', 'inorganic', 'chemistry', 'Inorganic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX140', 'Pauling''s Rules', 'Rules for ionic crystal structures', 'inorganic', 'chemistry', 'Inorganic Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX141', 'Beer''s Law', 'A = εbc', 'analytical', 'chemistry', 'Analytical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX142', 'Nernst Equation', 'E = E° - (RT/nF) ln Q', 'analytical', 'chemistry', 'Analytical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX143', 'Ilkovic Equation', 'i_d = 607nD^{1/2}m^{2/3}t^{1/6}C', 'analytical', 'chemistry', 'Analytical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX144', 'Stokes-Einstein', 'D = k_BT/(6πηr)', 'analytical', 'chemistry', 'Analytical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX145', 'van Deemter Equation', 'H = A + B/u + Cu', 'analytical', 'chemistry', 'Analytical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX146', 'Henderson-Hasselbalch', 'pH = pK_a + log([A⁻]/[HA])', 'analytical', 'chemistry', 'Analytical Chemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX147', 'Michaelis-Menten', 'v = V_max[S]/(K_m + [S])', 'biochem', 'chemistry', 'Biochemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX148', 'Lineweaver-Burk', '1/v = (K_m/V_max)(1/[S]) + 1/V_max', 'biochem', 'chemistry', 'Biochemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX149', 'Hill Equation', 'θ = [L]ⁿ/(K_d + [L]ⁿ)', 'biochem', 'chemistry', 'Biochemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX150', 'Scatchard Plot', '[B]/[F] = nK - K[B]', 'biochem', 'chemistry', 'Biochemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX151', 'Monod Equation', 'μ = μ_max[S]/(K_s + [S])', 'biochem', 'chemistry', 'Biochemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX152', 'Logistic Growth', 'dN/dt = rN(1 - N/K)', 'biochem', 'chemistry', 'Biochemistry');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX153', 'Hooke''s Law', 'σ = Eε', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX154', 'Poisson''s Ratio', 'ν = -ε_trans/ε_axial', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX155', 'Bulk Modulus', 'K = -V dP/dV', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX156', 'Shear Modulus', 'G = τ/γ', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX157', 'Young''s Modulus', 'E = σ/ε', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX158', 'Euler-Bernoulli Beam', 'EI d⁴y/dx⁴ = q(x)', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX159', 'Bending Stress', 'σ = My/I', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX160', 'Shear Stress', 'τ = VQ/(Ib)', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX161', 'Torsion', 'τ = Tr/J, θ = TL/(GJ)', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX162', 'Von Mises Stress', 'σ_v = √(σ₁² - σ₁σ₂ + σ₂² + 3τ²)', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX163', 'Tresca Criterion', 'τ_max = σ_yield/2', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX164', 'Mohr''s Circle', 'σ₁,₂ = (σ_x+σ_y)/2 ± √((σ_x-σ_y)/2)² + τ_xy²', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX165', 'Castigliano''s Theorem', 'δ = ∂U/∂P', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX166', 'St. Venant''s Principle', 'Stress distribution equalizes away from load', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX167', 'Saint-Venant''s Torsion', 'Warping function for non-circular sections', 'solids', 'mechanical', 'Solid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX168', 'Continuity Equation', '∇·v = 0', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX169', 'Euler''s Equation', 'ρ Dv/Dt = -∇p + ρg', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX170', 'Navier-Stokes', 'ρ Dv/Dt = -∇p + μ∇²v + ρg', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX171', 'Bernoulli Equation', 'p/ρ + v²/2 + gz = constant', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX172', 'Poiseuille Flow', 'Q = πR⁴ΔP/(8μL)', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX173', 'Couette Flow', 'u(y) = U·y/h', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX174', 'Blasius Boundary Layer', 'f'''''' + ff'''' = 0', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX175', 'Reynolds Number', 'Re = ρvL/μ', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX176', 'Froude Number', 'Fr = v/√(gL)', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX177', 'Mach Number', 'M = v/c', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX178', 'Weber Number', 'We = ρv²L/σ', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX179', 'Euler Number', 'Eu = ΔP/(ρv²)', 'fluids', 'mechanical', 'Fluid Mechanics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX180', 'Rankine Cycle Efficiency', 'η = (h₁-h₂)/(h₁-h₄)', 'thermo', 'mechanical', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX181', 'Brayton Cycle Efficiency', 'η = 1 - 1/r^{γ-1}', 'thermo', 'mechanical', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX182', 'Otto Cycle Efficiency', 'η = 1 - 1/r^{γ-1}', 'thermo', 'mechanical', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX183', 'Diesel Cycle Efficiency', 'η = 1 - (1/r^{γ-1})(r_c^γ-1)/(γ(r_c-1))', 'thermo', 'mechanical', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX184', 'Carnot Refrigeration COP', 'COP = T_L/(T_H - T_L)', 'thermo', 'mechanical', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX185', 'Psychrometrics', 'ω = 0.622 φP_s/(P-φP_s)', 'thermo', 'mechanical', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX186', 'Compressible Flow', 'T₀/T = 1 + (γ-1)/2·M²', 'thermo', 'mechanical', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX187', 'Isentropic Flow', 'P₀/P = (1 + (γ-1)/2·M²)^{γ/(γ-1)}', 'thermo', 'mechanical', 'Thermodynamics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX188', 'Fourier''s Law', 'q = -k∇T', 'heat', 'mechanical', 'Heat Transfer');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX189', 'Heat Equation', '∂T/∂t = α∇²T', 'heat', 'mechanical', 'Heat Transfer');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX190', 'Newton''s Law of Cooling', 'q = h(T_s - T_∞)', 'heat', 'mechanical', 'Heat Transfer');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX191', 'Stefan-Boltzmann Law', 'q = εσT⁴', 'heat', 'mechanical', 'Heat Transfer');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX192', 'Nusselt Number', 'Nu = hL/k', 'heat', 'mechanical', 'Heat Transfer');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX193', 'Biot Number', 'Bi = hL/k_s', 'heat', 'mechanical', 'Heat Transfer');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX194', 'Fourier Number', 'Fo = αt/L²', 'heat', 'mechanical', 'Heat Transfer');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX195', 'Log Mean Temperature Difference', 'ΔT_lm = (ΔT₁-ΔT₂)/ln(ΔT₁/ΔT₂)', 'heat', 'mechanical', 'Heat Transfer');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX196', 'Simple Harmonic Motion', 'x = A cos(ωt + φ)', 'vibration', 'mechanical', 'Vibration & Control');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX197', 'Damped Vibration', 'mẍ + cẋ + kx = 0', 'vibration', 'mechanical', 'Vibration & Control');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX198', 'Forced Vibration', 'mẍ + cẋ + kx = F₀ cos(ωt)', 'vibration', 'mechanical', 'Vibration & Control');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX199', 'Transmissibility', 'TR = √[(1+(2ζr)²)/((1-r²)²+(2ζr)²)]', 'vibration', 'mechanical', 'Vibration & Control');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX200', 'Modal Analysis', '[K - ω²M]φ = 0', 'vibration', 'mechanical', 'Vibration & Control');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX201', 'Ohm''s Law', 'V = IR', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX202', 'Kirchhoff''s Voltage Law', 'ΣV = 0', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX203', 'Kirchhoff''s Current Law', 'ΣI = 0', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX204', 'Power', 'P = VI = I²R = V²/R', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX205', 'AC Power', 'P = VI cosφ, Q = VI sinφ, S = VI', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX206', 'RC Time Constant', 'τ = RC', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX207', 'RL Time Constant', 'τ = L/R', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX208', 'RLC Resonance', 'ω₀ = 1/√(LC)', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX209', 'Quality Factor', 'Q = ω₀L/R = 1/(ω₀RC)', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX210', 'Bandwidth', 'BW = ω₀/Q', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX211', 'Thevenin Theorem', 'V_Th = V_oc, R_Th = V_oc/I_sc', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX212', 'Norton Theorem', 'I_N = I_sc, R_N = V_oc/I_sc', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX213', 'Superposition Theorem', 'Response = sum of individual source responses', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX214', 'Maximum Power Transfer', 'P_max when R_L = R_Th', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX215', 'Two-Port Parameters', '[V₁; V₂] = [z₁₁ z₁₂; z₂₁ z₂₂][I₁; I₂]', 'circuits', 'electrical', 'Circuit Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX216', 'Diode Equation', 'I = I_s(e^{V/(nV_T)} - 1)', 'electronics', 'electrical', 'Electronics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX217', 'BJT Current', 'I_C = I_S e^{V_BE/V_T}', 'electronics', 'electrical', 'Electronics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX218', 'MOSFET', 'I_D = (μC_ox/2)(W/L)(V_GS - V_T)²', 'electronics', 'electrical', 'Electronics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX219', 'Transconductance', 'g_m = ∂I_D/∂V_GS', 'electronics', 'electrical', 'Electronics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX220', 'Early Effect', 'I_C = I_S e^{V_BE/V_T}(1 + V_CE/V_A)', 'electronics', 'electrical', 'Electronics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX221', 'Miller Effect', 'C_in = C(1 + A_v)', 'electronics', 'electrical', 'Electronics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX222', 'Gain-Bandwidth Product', 'f_T = g_m/(2π(C_gs + C_gd))', 'electronics', 'electrical', 'Electronics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX223', 'Op-Amp Golden Rules', 'V+ = V-, I+ = I- = 0', 'electronics', 'electrical', 'Electronics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX224', 'Feedback', 'A_f = A/(1 + Aβ)', 'electronics', 'electrical', 'Electronics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX225', 'Oscillator', 'Barkhausen: |Aβ| = 1, ∠Aβ = 0°', 'electronics', 'electrical', 'Electronics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX226', 'Per Unit System', 'pu = actual/base', 'power', 'electrical', 'Power Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX227', 'Three-Phase Power', 'P = √3 V_L I_L cosφ', 'power', 'electrical', 'Power Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX228', 'Transformer Equation', 'V₁/V₂ = N₁/N₂', 'power', 'electrical', 'Power Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX229', 'Induction Motor Torque', 'T = (3/ω_s)·(V²(R₂/s)/((R₁+R₂/s)²+(X₁+X₂)²))', 'power', 'electrical', 'Power Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX230', 'Synchronous Machine', 'P = (EV/X) sinδ', 'power', 'electrical', 'Power Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX231', 'Power Flow', 'P = (V₁V₂/X) sinδ', 'power', 'electrical', 'Power Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX232', 'Fault Current', 'I_f = V/Z_th', 'power', 'electrical', 'Power Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX233', 'Swing Equation', 'M d²δ/dt² = P_m - P_e', 'power', 'electrical', 'Power Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX234', 'Transfer Function', 'G(s) = Y(s)/U(s)', 'control', 'electrical', 'Control Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX235', 'PID Controller', 'u(t) = K_p e(t) + K_i ∫e dt + K_d de/dt', 'control', 'electrical', 'Control Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX236', 'Root Locus', '1 + KG(s) = 0', 'control', 'electrical', 'Control Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX237', 'Bode Plot', '|G(jω)|, ∠G(jω) vs ω', 'control', 'electrical', 'Control Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX238', 'Nyquist Stability', 'N = Z - P', 'control', 'electrical', 'Control Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX239', 'State Space', 'ẋ = Ax + Bu, y = Cx + Du', 'control', 'electrical', 'Control Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX240', 'Controllability', 'rank[B AB A²B ...] = n', 'control', 'electrical', 'Control Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX241', 'Observability', 'rank[C CA CA² ...]ᵀ = n', 'control', 'electrical', 'Control Systems');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX242', 'Fourier Transform', 'F(ω) = ∫ f(t)e^{-iωt}dt', 'signal', 'electrical', 'Signal Processing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX243', 'Laplace Transform', 'F(s) = ∫ f(t)e^{-st}dt', 'signal', 'electrical', 'Signal Processing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX244', 'Z-Transform', 'X(z) = Σ x[n]z⁻ⁿ', 'signal', 'electrical', 'Signal Processing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX245', 'Convolution', 'y[n] = x[n] * h[n]', 'signal', 'electrical', 'Signal Processing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX246', 'Sampling Theorem', 'f_s ≥ 2f_max', 'signal', 'electrical', 'Signal Processing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX247', 'DFT', 'X[k] = Σ x[n]e^{-j2πkn/N}', 'signal', 'electrical', 'Signal Processing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX248', 'Maxwell''s Equations', '∇·E = ρ/ε₀, ∇·B = 0, ∇×E = -∂B/∂t, ∇×B = μ₀J + μ₀ε₀∂E/∂t', 'emag', 'electrical', 'Electromagnetics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX249', 'Wave Equation', '∇²E = με ∂²E/∂t²', 'emag', 'electrical', 'Electromagnetics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX250', 'Poynting Vector', 'S = E × H', 'emag', 'electrical', 'Electromagnetics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX251', 'Transmission Line', 'Z₀ = √((R+jωL)/(G+jωC))', 'emag', 'electrical', 'Electromagnetics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX252', 'Antenna Gain', 'G = 4πU/P_in', 'emag', 'electrical', 'Electromagnetics');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX253', 'Fuel Consumption', 'FC = a·v² + b·v + c + d·load', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX254', 'Braking Distance', 'd = v²/(2μg)', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX255', 'Aerodynamic Drag', 'F_d = ½ρv²C_dA', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX256', 'Rolling Resistance', 'F_r = C_r·W', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX257', 'Grade Resistance', 'F_g = W·sinθ', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX258', 'Engine Power', 'P = F·v', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX259', 'Torque Curve', 'T = T_max·(1 - e^{-kω})', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX260', 'Transmission Efficiency', 'η = P_out/P_in', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX261', 'Tire Wear', 'w = k·Fⁿ·v·t', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX262', 'KTRUCK Payload', 'P = P_max·(1 - e^{-kt})', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX263', 'Route Optimization', 'min Σ (t_i·c_i + d_i·f_i)', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX264', 'Fleet Utilization', 'U = Σ (active_time)/total_time', 'trucking', 'transportation', 'Trucking');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX265', 'Tractive Effort', 'F = μ·W·(1 - e^{-kv})', 'railroad', 'transportation', 'Railroad');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX266', 'Rolling Resistance', 'R = A + Bv + Cv²', 'railroad', 'transportation', 'Railroad');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX267', 'Curve Resistance', 'R_c = k·W/R', 'railroad', 'transportation', 'Railroad');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX268', 'Grade Resistance', 'R_g = W·sinθ', 'railroad', 'transportation', 'Railroad');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX269', 'Davis Equation', 'R = a + bv + cAv²', 'railroad', 'transportation', 'Railroad');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX270', 'Train Dynamics', 'M·dv/dt = F - R(v)', 'railroad', 'transportation', 'Railroad');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX271', 'Braking Force', 'F_b = μ·N·n', 'railroad', 'transportation', 'Railroad');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX272', 'KTRACK Rail Wear', 'w = k·T·N', 'railroad', 'transportation', 'Railroad');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX273', 'Scheduling', 'T = Σ(t_i + d_i)', 'railroad', 'transportation', 'Railroad');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX274', 'Headway', 'H = L/v + t_s', 'railroad', 'transportation', 'Railroad');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX275', 'Engine Power', 'P = T·ω', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX276', 'Vehicle Acceleration', 'a = (F_t - F_r - F_d)/m', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX277', 'Fuel Economy', 'FE = v/FC', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX278', 'BSFC', 'BSFC = ṁ_f/P', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX279', 'Gear Ratio', 'i = ω_e/ω_w', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX280', 'Drivetrain Loss', 'η = P_w/P_e', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX281', 'Lateral Acceleration', 'a_y = v²/R', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX282', 'Understeer Gradient', 'K = (δ - L/R)/a_y', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX283', 'Brake Balance', 'β = F_f/F_total', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX284', 'EV Range', 'R = E_bat / (P_aux + P_trac/η)', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX285', 'Regenerative Braking', 'E_recov = η·½m(v₁² - v₂²)', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX286', 'Battery Model', 'V = V_oc - I·R_int', 'automotive', 'transportation', 'Automotive');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX287', 'Lift', 'L = ½ρv²·C_L·A', 'aerospace', 'transportation', 'Aerospace');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX288', 'Drag', 'D = ½ρv²·C_D·A', 'aerospace', 'transportation', 'Aerospace');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX289', 'Thrust', 'F = ṁ·v_e + (p_e - p₀)·A_e', 'aerospace', 'transportation', 'Aerospace');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX290', 'Rocket Equation', 'Δv = v_e·ln(m₀/m_f)', 'aerospace', 'transportation', 'Aerospace');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX291', 'Specific Impulse', 'I_sp = F/(ṁ·g₀)', 'aerospace', 'transportation', 'Aerospace');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX292', 'Mach Number', 'M = v/c', 'aerospace', 'transportation', 'Aerospace');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX293', 'Glide Ratio', 'L/D = C_L/C_D', 'aerospace', 'transportation', 'Aerospace');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX294', 'Orbital Velocity', 'v = √(GM/r)', 'aerospace', 'transportation', 'Aerospace');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX295', 'Hull Resistance', 'R_total = R_f + R_w + R_app', 'marine', 'transportation', 'Marine');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX296', 'Froude Number', 'Fr = v/√(gL)', 'marine', 'transportation', 'Marine');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX297', 'Propeller Thrust', 'T = ρ·n²·D⁴·K_T', 'marine', 'transportation', 'Marine');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX298', 'Black-Scholes PDE', '∂V/∂t + ½σ²S²∂²V/∂S² + rS∂V/∂S - rV = 0', 'derivatives', 'financial', 'Derivatives');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX299', 'Black-Scholes Call', 'C = S·N(d₁) - K·e^{-rT}·N(d₂)', 'derivatives', 'financial', 'Derivatives');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX300', 'd₁ formula', 'd₁ = [ln(S/K) + (r + σ²/2)T]/(σ√T)', 'derivatives', 'financial', 'Derivatives');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX301', 'd₂ formula', 'd₂ = d₁ - σ√T', 'derivatives', 'financial', 'Derivatives');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX302', 'Put-Call Parity', 'C - P = S - K·e^{-rT}', 'derivatives', 'financial', 'Derivatives');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX303', 'Binomial Tree', 'S_u = S·u, S_d = S·d', 'derivatives', 'financial', 'Derivatives');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX304', 'Risk-Neutral Probability', 'p = (e^{rΔt} - d)/(u - d)', 'derivatives', 'financial', 'Derivatives');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX305', 'Delta', 'Δ = ∂V/∂S', 'derivatives', 'financial', 'Derivatives');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX306', 'Gamma', 'Γ = ∂²V/∂S²', 'derivatives', 'financial', 'Derivatives');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX307', 'Vega', 'ν = ∂V/∂σ', 'derivatives', 'financial', 'Derivatives');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX308', 'CAPM', 'E(Rᵢ) = R_f + βᵢ(E(R_m) - R_f)', 'asset', 'financial', 'Asset Pricing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX309', 'Beta', 'βᵢ = Cov(Rᵢ,R_m)/Var(R_m)', 'asset', 'financial', 'Asset Pricing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX310', 'APT', 'Rᵢ = E(Rᵢ) + β₁F₁ + β₂F₂ + ... + εᵢ', 'asset', 'financial', 'Asset Pricing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX311', 'Fama-French 3-Factor', 'Rᵢ - R_f = α + β₁(R_m - R_f) + β₂SMB + β₃HML + ε', 'asset', 'financial', 'Asset Pricing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX312', 'Sharpe Ratio', 'S = (R_p - R_f)/σ_p', 'asset', 'financial', 'Asset Pricing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX313', 'Treynor Ratio', 'T = (R_p - R_f)/β_p', 'asset', 'financial', 'Asset Pricing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX314', 'Jensen''s Alpha', 'α = R_p - [R_f + β_p(R_m - R_f)]', 'asset', 'financial', 'Asset Pricing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX315', 'Information Ratio', 'IR = α/σ_ε', 'asset', 'financial', 'Asset Pricing');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX316', 'Value at Risk', 'VaRₐ = μ - σ·Φ⁻¹(α)', 'risk', 'financial', 'Risk Management');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX317', 'Conditional VaR', 'CVaR = E[X|X < VaR]', 'risk', 'financial', 'Risk Management');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX318', 'Expected Shortfall', 'ES = (1/(1-α))∫_α¹ VaR_u du', 'risk', 'financial', 'Risk Management');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX319', 'Stress Testing', 'Scenario-based risk assessment', 'risk', 'financial', 'Risk Management');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX320', 'Scenario Analysis', 'What-if analysis', 'risk', 'financial', 'Risk Management');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX321', 'Credit VaR', 'Credit risk metrics', 'risk', 'financial', 'Risk Management');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX322', 'Duration', 'D = - (1/P)(dP/dy)', 'risk', 'financial', 'Risk Management');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX323', 'Convexity', 'C = (1/P)(d²P/dy²)', 'risk', 'financial', 'Risk Management');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX324', 'Markowitz Mean-Variance', 'min σ_p² s.t. E[R_p] = target', 'portfolio', 'financial', 'Portfolio Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX325', 'Efficient Frontier', 'Set of optimal portfolios', 'portfolio', 'financial', 'Portfolio Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX326', 'Capital Market Line', 'E[R_p] = R_f + (E[R_m] - R_f)(σ_p/σ_m)', 'portfolio', 'financial', 'Portfolio Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX327', 'Security Market Line', 'E[Rᵢ] = R_f + βᵢ(E[R_m] - R_f)', 'portfolio', 'financial', 'Portfolio Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX328', 'Diversification', 'σ_p² = Σwᵢ²σᵢ² + ΣΣwᵢwⱼσᵢⱼ', 'portfolio', 'financial', 'Portfolio Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX329', 'Black-Litterman Model', 'E[R] = [(τΣ)^{-1} + PᵀΩ^{-1}P]^{-1}[(τΣ)^{-1}Π + PᵀΩ^{-1}Q]', 'portfolio', 'financial', 'Portfolio Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX330', 'Bond Pricing', 'P = Σ C/(1+y)ᵗ + F/(1+y)ᵀ', 'fixed', 'financial', 'Fixed Income');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX331', 'Yield to Maturity', 'P = Σ C/(1+YTM)ᵗ + F/(1+YTM)ᵀ', 'fixed', 'financial', 'Fixed Income');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX332', 'Spot Rate', 'Zero-coupon yield', 'fixed', 'financial', 'Fixed Income');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX333', 'Forward Rate', '(1+f)ᵗ = (1+s_{t})ᵗ/(1+s_{t-1})ᵗ⁻¹', 'fixed', 'financial', 'Fixed Income');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX334', 'SHA-256 Hash', 'H = SHA-256(message)', 'fintech', 'financial', 'FinTech');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX335', 'Merkle Tree', 'root = H(H(a)||H(b))', 'fintech', 'financial', 'FinTech');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX336', 'Proof of Work', 'H(n||h) < target', 'fintech', 'financial', 'FinTech');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX337', 'Smart Contract Gas', 'gas = Σ opcode_cost', 'fintech', 'financial', 'FinTech');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX338', 'Binary Search', 'T(n) = T(n/2) + O(1) = O(log n)', 'algorithms', 'computerscience', 'Algorithms');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX339', 'Merge Sort', 'T(n) = 2T(n/2) + O(n) = O(n log n)', 'algorithms', 'computerscience', 'Algorithms');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX340', 'Quick Sort', 'T(n) = T(k) + T(n-k-1) + O(n)', 'algorithms', 'computerscience', 'Algorithms');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX341', 'Dijkstra''s Algorithm', 'O((V+E) log V)', 'algorithms', 'computerscience', 'Algorithms');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX342', 'Bellman-Ford', 'O(VE)', 'algorithms', 'computerscience', 'Algorithms');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX343', 'Floyd-Warshall', 'O(V³)', 'algorithms', 'computerscience', 'Algorithms');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX344', 'Knapsack Problem', 'DP[n][W] = max(DP[n-1][W], DP[n-1][W-w[n]] + v[n])', 'algorithms', 'computerscience', 'Algorithms');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX345', 'Longest Common Subsequence', 'DP[i][j] = DP[i-1][j-1]+1 if match else max(DP[i-1][j], DP[i][j-1])', 'algorithms', 'computerscience', 'Algorithms');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX346', 'KMP Algorithm', 'O(n+m) string matching', 'algorithms', 'computerscience', 'Algorithms');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX347', 'RSA Encryption', 'C = Mᵉ mod n, M = Cᵈ mod n', 'algorithms', 'computerscience', 'Algorithms');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX348', 'P vs NP', 'P = {problems solvable in polynomial time}', 'complexity', 'computerscience', 'Complexity');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX349', 'NP-Completeness', 'NP-complete = NP ∩ NP-hard', 'complexity', 'computerscience', 'Complexity');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX350', 'Cook-Levin Theorem', 'SAT is NP-complete', 'complexity', 'computerscience', 'Complexity');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX351', 'Time Hierarchy Theorem', 'DTIME(f(n)) ⊊ DTIME(f(n)log²f(n))', 'complexity', 'computerscience', 'Complexity');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX352', 'Space Hierarchy Theorem', 'DSPACE(f(n)) ⊊ DSPACE(f(n)log f(n))', 'complexity', 'computerscience', 'Complexity');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX353', 'Linear Regression', 'y = wᵀx + b', 'ml', 'computerscience', 'Machine Learning');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX354', 'Logistic Regression', 'P(y=1|x) = 1/(1+e^{-wᵀx})', 'ml', 'computerscience', 'Machine Learning');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX355', 'SVM', 'max 1/||w|| s.t. yᵢ(wᵀxᵢ + b) ≥ 1', 'ml', 'computerscience', 'Machine Learning');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX356', 'Neural Network', 'a⁽ˡ⁾ = σ(W⁽ˡ⁾a⁽ˡ⁻¹⁾ + b⁽ˡ⁾)', 'ml', 'computerscience', 'Machine Learning');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX357', 'Backpropagation', 'δ⁽ˡ⁾ = (w⁽ˡ⁺¹⁾)ᵀδ⁽ˡ⁺¹⁾ ⊙ σ''(z⁽ˡ⁾)', 'ml', 'computerscience', 'Machine Learning');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX358', 'Gradient Descent', 'w ← w - η∇L(w)', 'ml', 'computerscience', 'Machine Learning');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX359', 'PCA', 'max Var(wᵀX) s.t. ||w||=1', 'ml', 'computerscience', 'Machine Learning');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX360', 'K-means', 'min Σ||x - μ||²', 'ml', 'computerscience', 'Machine Learning');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX361', 'Shannon Entropy', 'H(X) = -Σ p(x) log p(x)', 'info', 'computerscience', 'Information Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX362', 'Mutual Information', 'I(X;Y) = H(X) - H(X|Y)', 'info', 'computerscience', 'Information Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX363', 'KL Divergence', 'D_KL(P||Q) = Σ p(x) log(p(x)/q(x))', 'info', 'computerscience', 'Information Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX364', 'Channel Capacity', 'C = max I(X;Y)', 'info', 'computerscience', 'Information Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX365', 'Shannon-Hartley', 'C = B log₂(1 + S/N)', 'info', 'computerscience', 'Information Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX366', 'Rate-Distortion', 'R(D) = min I(X;X̂) s.t. E[d(X,X̂)] ≤ D', 'info', 'computerscience', 'Information Theory');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX367', 'RSA', 'ed ≡ 1 (mod φ(n))', 'crypto', 'computerscience', 'Cryptography');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX368', 'AES', 'SubBytes, ShiftRows, MixColumns, AddRoundKey', 'crypto', 'computerscience', 'Cryptography');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX369', 'Diffie-Hellman', 'g^{ab} mod p', 'crypto', 'computerscience', 'Cryptography');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX370', 'ECC', 'y² = x³ + ax + b', 'crypto', 'computerscience', 'Cryptography');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX371', 'Digital Signature', 'Sign(priv, msg), Verify(pub, sig, msg)', 'crypto', 'computerscience', 'Cryptography');
INSERT INTO axioms (serial, name, equation, family, domain, category) VALUES ('AX372', 'Zero-Knowledge Proof', 'Prover convinces Verifier without revealing secret', 'crypto', 'computerscience', 'Cryptography');
